# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql:8
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      TZ: Asia/Tokyo
    ports:
    - 3306:3306
